#!/bin/sh

set -eu

show_usage() {
    echo "Usage: newsigningkey KEY_PATH

Generate a new key-pair for signing file downloads.

Options:
  -s SIZE -- generate a key of size SIZE (default: 4096)
  -t TYPE -- one of: GPG, RSA"
}

main() {
    local size type
    size=4096
    type=rsa

    local OPTIND
    while getopts hs:t: opt; do
        case "$opt" in
            h) show_usage; exit ;;
            s) size="$OPTARG" ;;
            t) type="$(printf '%s' "$OPTARG" | tr '[:upper:]' '[:lower:]')" ;;
        esac
    done
    shift $(( OPTIND - 1 ))

    if [ $# -lt 1 ]; then
      show_usage
      exit 1
    fi

    case "$type" in
      gpg) ;;
      rsa) ;;
      *) show_usage; exit 1 ;;
    esac

    generate_${type}_key "$1"
}

generate_rsa_key() {
    if ! hash openssl; then
      echo "Error: openssl not installed" >&2
      exit 1
    fi

    openssl genrsa -out "$1" "$size"

    echo "Writing public key to $1.pub" >&2
    openssl rsa -in "$1" -pubout -out "$1.pub" 2>/dev/null

    echo "Writing Microsoft public key to $1.mspub" >&2
    openssl rsa -in "$1" -pubout -outform 'MS PUBLICKEY' 2>/dev/null | xxd -p >| "$1.mspub"
}

main "$@"
